// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_NtUcaSNl8uQiDLWtqpdZjYrPj4Mk66I',
    appId: '1:231454825672:web:c3eb2a11aa6a93d1ab99fd',
    messagingSenderId: '231454825672',
    projectId: 'uptp-control',
    authDomain: 'uptp-control.firebaseapp.com',
    storageBucket: 'uptp-control.firebasestorage.app',
    measurementId: 'G-T48KXWXYHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQwe9DFqJUJCRywgqOcBdhYpi0nX2sBNU',
    appId: '1:231454825672:android:6c5588aa91bff612ab99fd',
    messagingSenderId: '231454825672',
    projectId: 'uptp-control',
    storageBucket: 'uptp-control.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKOubWvOv9qVDf2FhjGRphcIID2A0dRV4',
    appId: '1:231454825672:ios:3db572a439908e1eab99fd',
    messagingSenderId: '231454825672',
    projectId: 'uptp-control',
    storageBucket: 'uptp-control.firebasestorage.app',
    iosBundleId: 'com.uptp.uptpControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKOubWvOv9qVDf2FhjGRphcIID2A0dRV4',
    appId: '1:231454825672:ios:3db572a439908e1eab99fd',
    messagingSenderId: '231454825672',
    projectId: 'uptp-control',
    storageBucket: 'uptp-control.firebasestorage.app',
    iosBundleId: 'com.uptp.uptpControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_NtUcaSNl8uQiDLWtqpdZjYrPj4Mk66I',
    appId: '1:231454825672:web:f079ee1cc95efea5ab99fd',
    messagingSenderId: '231454825672',
    projectId: 'uptp-control',
    authDomain: 'uptp-control.firebaseapp.com',
    storageBucket: 'uptp-control.firebasestorage.app',
    measurementId: 'G-NRTB438NVR',
  );
}